spring.data.mongodb.uri=mongodb+srv://ankushsharma00869:Ankush%402006@cloudshare.g64rnkh.mongodb.net/cloudshare?retryWrites=true&w=majorityspring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
server.servlet.context-path=/api/v1.0
clerk.jwks-url=https://winning-tiger-63.clerk.accounts.dev/.well-known/jwks.json

clerk.issuer=https://winning-tiger-63.clerk.accounts.dev
clerk.webhook.secret=s61ym4RnINKEnD3MZqTVqDXgk2fRL4iO


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
razorpay.key.id=rzp_test_ScEeOiryx8MrZo
razorpay.key.secret=tNh12ViN4cZaSInNdSWehfue